import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/layouts/footer';
import { Great_Vibes, Open_Sans, Raleway } from 'next/font/google';
// import { Lato, Playfair_Display } from 'next/font/google';
import { cn } from '@/lib/utils';
import Navbar from '@/layouts/navbar';

// const fontTitle = Playfair_Display({
// 	subsets: ['latin'],
// 	display: 'swap',
// 	variable: '--font-title',
// 	weight: ['400', '500', '700'],
// });

// const fontBody = Lato({
// 	subsets: ['latin'],
// 	display: 'swap',
// 	variable: '--font-body',
// 	weight: ['300', '400', '700'],
// });

const fontTitle = Raleway({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-title',
	weight: ['400', '500', '700'],
});

const fontBody = Open_Sans({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-body',
	weight: ['300', '400', '700'],
});

const fontNavbarTitle = Great_Vibes({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-navbar-title',
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'O Marisco',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					'antialiased',
					fontBody.variable,
					fontTitle.variable,
					fontNavbarTitle.variable
				)}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
